Repository aws/aws-cli, pull requests merged in 2018-07, with the labels that each got.

#3355 updated description for source-group parameter
  awscli/customizations/ec2/secgroupsimplify.py
Labels: response-needed

#3389 New and updated AWS CodeCommit examples
  awscli/examples/codecommit/create-pull-request.rst
  awscli/examples/codecommit/delete-comment-content.rst
  awscli/examples/codecommit/describe-pull-request-events.rst
  awscli/examples/codecommit/get-blob.rst
  awscli/examples/codecommit/get-comment.rst
  awscli/examples/codecommit/get-comments-for-compared-commit.rst
  awscli/examples/codecommit/get-comments-for-pull-request.rst
  awscli/examples/codecommit/get-commit.rst
  awscli/examples/codecommit/get-differences.rst
  awscli/examples/codecommit/get-merge-conflicts.rst
  awscli/examples/codecommit/get-pull-request.rst
  awscli/examples/codecommit/get-repository-triggers.rst
  awscli/examples/codecommit/list-pull-requests.rst
  awscli/examples/codecommit/merge-pull-request-by-fast-forward.rst
  awscli/examples/codecommit/post-comment-for-compared-commit.rst
  awscli/examples/codecommit/post-comment-for-pull-request.rst
  awscli/examples/codecommit/post-comment-reply.rst
  awscli/examples/codecommit/put-file.rst
  awscli/examples/codecommit/put-repository-triggers.rst
  awscli/examples/codecommit/test-repository-triggers.rst
  awscli/examples/codecommit/update-comment.rst
  awscli/examples/codecommit/update-pull-request-description.rst
  awscli/examples/codecommit/update-pull-request-status.rst
  awscli/examples/codecommit/update-pull-request-title.rst
Labels: changes-requested

#3177 Fix datapipeline CLI args for multi-value params
  awscli/customizations/datapipeline/__init__.py
  tests/unit/customizations/datapipeline/test_arg_parse.py
Labels: enhancement, needs-additional-reviewer, small
