Repository aws/aws-cli, pull requests merged in 2019-04, with the labels that each got.

#4050 Improve s3 integ test robustness
  awscli/testutils.py
  tests/integration/customizations/s3/test_plugin.py
Labels: small

#2901 aws cloudformation package: follow symlinks when packging
  awscli/customizations/cloudformation/artifact_exporter.py
Labels: changes-requested, cloudformation package/deploy, feature-request, small

#3929 Updated output for describe-activations
  awscli/examples/ssm/describe-activations.rst
Labels: changes-requested

#4081 Support Chinese regions in the S3Uploader
  .changes/next-release/bugfix-Cloudformation-75127.json
  awscli/customizations/cloudformation/deploy.py
  awscli/customizations/cloudformation/package.py
  awscli/customizations/s3uploader.py
  awscli/customizations/servicecatalog/generatebase.py
  tests/unit/customizations/cloudformation/test_deploy.py
  tests/unit/customizations/test_s3uploader.py
Labels: bug
