Repository aws/aws-cli, pull requests merged in 2020-11, with the labels that each got.

#5690 remove duplicate example 3 and example 4
  awscli/examples/kms/get-public-key.rst
Labels: documentation, pr/ready-to-merge

#5683 Fixing typo on example for medialive
  awscli/examples/medialive/create-channel.rst
  awscli/examples/medialive/create-input.rst
Labels: documentation, pr/ready-to-merge

#5663 Add paramfile exception for sesv2 put-account-details website-uri.
  awscli/paramfile.py
  tests/functional/sesv2/__init__.py
  tests/functional/sesv2/test_put_account_details.py
Labels: contribution/core, pr/needs-review, sesv2

#5647 missing comma on example
  awscli/examples/emr/create-cluster-examples.rst
Labels: documentation, pr/ready-to-merge

#5607 fixed typo
  exe/assets/README.md
Labels: documentation, pr/needs-review
