Repository aws/aws-cli, pull requests merged in 2021-03, with the labels that each got.

#5949 Add link to verify object integrity during upload
  awscli/topics/s3-faq.rst
Labels: documentation, pr/needs-review

#5914 Minor Getting Help change
  README.rst
Labels: contribution/core, pr/ready-to-merge

#5981 Pass O_TRUNC when rewriting kubeconfig
  awscli/customizations/eks/kubeconfig.py
  tests/unit/customizations/eks/test_kubeconfig.py
Labels: bug, customization, eks-kubeconfig, pr/ready-to-merge

#6018 Update build status badge
  README.rst
Labels: contribution/core
