Repository aws/aws-cli, pull requests merged in 2021-04, with the labels that each got.

#5995 add init to ecs customization tests
  tests/functional/ecs/__init__.py
  tests/functional/ecs/test_execute_command.py
Labels: contribution/core, pr/work-in-progress

#5574 fixes helptext for emr list-clusters --created-before option
  awscli/customizations/emr/helptext.py
Labels: emr, pr/ready-to-merge

#3306 Correct acm request-certificate example for --options
  awscli/examples/acm/request-certificate.rst
Labels: documentation, pr/ready-to-merge

#5910 SNS phone number opt-in example must include country code
  awscli/examples/sns/opt-in-phone-number.rst
Labels: documentation, pr/ready-to-merge

#6063 Fixed typo in "examples/ec2/copy-snapshot.rst"
  awscli/examples/ec2/copy-snapshot.rst
Labels: documentation, pr/ready-to-merge

#6110 [docs] fix example for "update apikey name"
  awscli/examples/apigateway/update-api-key.rst
Labels: documentation, pr/ready-to-merge
