Repository aws/aws-cli, pull requests merged in 2022-04, with the labels that each got.

#6301 Fixed aws-cli documentation for describe-clusters
  awscli/customizations/emr/describecluster.py
  awscli/customizations/emr/helptext.py
Labels: documentation, contribution:core, ready-for-review

#6558 Update S3 sync examples
  awscli/examples/s3/sync.rst
Labels: documentation, contribution:core

#3199 Clarify environment credential source documentation
  awscli/topics/config-vars.rst
Labels: documentation, contribution:core, needs-review

#3139 Append a newline to config files if needed
  .changes/next-release/bugfix-Configuration-17224.json
  awscli/customizations/configure/writer.py
  tests/unit/customizations/configure/test_writer.py
Labels: pr:needs-review, configuration, contribution:core

#6536 Add --use-json to cloudformation package example
  awscli/examples/cloudformation/package.rst
Labels: documentation, cloudformation package-deploy, customization

#6321 Update deprecated Runtime
  awscli/examples/lambda/create-function.rst
Labels: documentation

#6548 Validate description for iam new-role wizard
  awscli/customizations/wizard/wizards/iam/new-role.yml
Labels: wizard

#6551 Replace file:// with fileb:// in kafka create-configuration documentation
  awscli/examples/kafka/create-configuration.rst
Labels: documentation, kafka

#6783 ddb `select` output error handling
  .changes/next-release/bugfix-ddb-13616.json
  awscli/customizations/dynamodb/subcommands.py
  awscli/topics/return-codes.rst
  tests/functional/ddb/test_select.py
Labels: community, ready-for-review

#6170 Add quotes to the last parameter in the command
  awscli/examples/ec2/update-security-group-rule-descriptions-ingress.rst
Labels: documentation

#6143 Fix truncating zero microseconds in `logs tail` output
  .changes/next-release/bugfix-logs-57586.json
  awscli/customizations/logs/tail.py
  tests/unit/customizations/logs/test_tail.py
Labels: contribution:core
