Repository aws/aws-cli, pull requests merged in 2022-03, with the labels that each got.

#6780 Fix URL, causes an error when rendering help.
  awscli/examples/cloudformation/update-stack.rst
Labels: documentation, contribution:core

#6352 [v2][proposal] Installing AWS CLI v2 from source
  proposals/source-install.md
  setup.cfg
Labels: v2

#6791 Update copy-image.rst
  awscli/examples/ec2/copy-image.rst
Labels: documentation
