Repository aws/aws-cli, pull requests merged in 2022-05, with the labels that each got.

#5944 Fix s3 cp example for grants to specific users
  awscli/examples/s3/cp.rst
Labels: documentation, pr:needs-review, community

#6933 New CLI examples for pinpoint, ivschat, ec2, grafana, gamelift, compr…
  awscli/examples/comprehendmedical/describe-snomedct-inference-job.rst
  awscli/examples/comprehendmedical/infer-snomedct.rst
  awscli/examples/comprehendmedical/list-snomedct-inference-jobs.rst
  awscli/examples/comprehendmedical/start-snomedct-inference-job.rst
  awscli/examples/comprehendmedical/stop-snomedct-inference-job.rst
  awscli/examples/dms/describe-replication-tasks.rst
  awscli/examples/ec2/accept-transit-gateway-vpc-attachment.rst
  awscli/examples/ec2/attach-vpn-gateway.rst
  awscli/examples/ec2/create-transit-gateway.rst
  awscli/examples/ec2/create-vpc-endpoint.rst
  awscli/examples/ec2/create-vpc.rst
  awscli/examples/ec2/describe-instances.rst
  awscli/examples/ec2/describe-subnets.rst
  awscli/examples/ec2/describe-traffic-mirror-filters.rst
  awscli/examples/ec2/modify-traffic-mirror-session.rst
  awscli/examples/ec2/modify-vpn-tunnel-options.rst
  awscli/examples/ec2/search-local-gateway-routes.rst
  awscli/examples/gamelift/describe-game-session-queues.rst
  awscli/examples/grafana/list-workspaces.rst
  awscli/examples/ivschat/create-chat-token.rst
  awscli/examples/ivschat/create-room.rst
  awscli/examples/ivschat/delete-message.rst
  awscli/examples/ivschat/delete-room.rst
  awscli/examples/ivschat/disconnect-user.rst
  awscli/examples/ivschat/get-room.rst
  awscli/examples/ivschat/list-rooms.rst
  awscli/examples/ivschat/list-tags-for-resource.rst
  awscli/examples/ivschat/send-event.rst
  awscli/examples/ivschat/tag-resource.rst
  awscli/examples/ivschat/untag-resource.rst
  awscli/examples/ivschat/update-room.rst
  awscli/examples/pinpoint/get-apns-channel.rst
  awscli/examples/pinpoint/get-app.rst
  awscli/examples/pinpoint/get-campaign.rst
  awscli/examples/pinpoint/get-campaigns.rst
  awscli/examples/pinpoint/get-channels.rst
  awscli/examples/pinpoint/get-email-channel.rst
  awscli/examples/pinpoint/get-endpoint.rst
  awscli/examples/pinpoint/get-gcm-channel.rst
  awscli/examples/pinpoint/get-sms-channel.rst
  awscli/examples/pinpoint/get-voice-channel.rst
  awscli/examples/s3/presign.rst
  awscli/examples/s3api/get-object-attributes.rst
Labels: contribution:core

#3322 Updating update-certificate-options.rst
  awscli/examples/acm/add-tags-to-certificate.rst
  awscli/examples/acm/delete-certificate.rst
  awscli/examples/acm/describe-certificate.rst
  awscli/examples/acm/export-certificate.rst
  awscli/examples/acm/get-certificate.rst
  awscli/examples/acm/import-certificate.rst
  awscli/examples/acm/list-certificates.rst
  awscli/examples/acm/list-tags-for-certificate.rst
  awscli/examples/acm/remove-tags-from-certificate.rst
  awscli/examples/acm/resend-validation-email.rst
Labels: documentation, feature-request, enhancement

#4014 Fix a few typos
  awscli/alias.py
  awscli/customizations/argrename.py
  awscli/customizations/awslambda.py
  awscli/customizations/cloudformation/yamlhelper.py
  awscli/customizations/cloudfront.py
  awscli/customizations/configservice/subscribe.py
  awscli/customizations/configure/addmodel.py
  awscli/customizations/emr/helptext.py
  awscli/customizations/history/__init__.py
  awscli/customizations/history/show.py
  awscli/customizations/paginate.py
  awscli/customizations/s3/fileformat.py
  awscli/customizations/s3/filegenerator.py
  awscli/customizations/s3/fileinfo.py
  awscli/customizations/s3/filters.py
  awscli/customizations/utils.py
  awscli/topictags.py
  bin/aws_zsh_completer.sh
Labels: documentation

#3843 Update describe-regions.rst
  awscli/examples/ec2/describe-regions.rst
Labels: documentation, pr:blocked

#5491 rectified set-endpoint-attributes.rst [get->set]
  awscli/examples/sns/get-endpoint-attributes.rst
  awscli/examples/sns/set-endpoint-attributes.rst
Labels: documentation, pr:needs-review

#4026 Update sample command set-identity-pool-roles
  awscli/examples/cognito-identity/set-identity-pool-roles.rst
Labels: documentation

#4135 Added missing --user-attributes flag
  awscli/examples/cognito-idp/admin-update-user-attributes.rst
Labels: documentation, pr:ready-to-merge

#5915 Merge v1 Getting Help and Resources updates
  README.rst
Labels: pr:ready-to-merge, contribution:core

#5152 Removed redundant parser assignment
  awscli/clidriver.py
Labels: implementation, community

#3791 Lambda and Serverless properties for CFN deploy
  awscli/examples/cloudformation/_package_description.rst
Labels: documentation, cloudformation package-deploy, customization, community

#5741 Add link to more info for configuring sso.
  awscli/customizations/configure/sso.py
Labels: pr:work-in-progress, contribution:core

#4824 For sequences, (strings, lists, tuples), use the fact that empty sequences are false.
  awscli/customizations/emr/createcluster.py
Labels: response-requested, customization, implementation, community, needs-rebase

#4694 Adding to CloudFormation's URL parameters
  awscli/paramfile.py
  tests/functional/cloudformation/test_register_type.py
Labels: cloudformation package-deploy, customization, implementation, community

#4353 Delete unused variable
  awscli/clidocs.py
  awscli/customizations/emr/describecluster.py
  awscli/customizations/emr/instancefleetsutils.py
  awscli/customizations/toplevelbool.py
Labels: community, ready-for-review

#3822 Add support for aws cloudformation package of AWS::AppSync::FunctionC…
  awscli/examples/cloudformation/_package_description.rst
Labels: cloudformation package-deploy, customization, community

#6991 Update v2 README supported Python versions to 3.8, 3.9
  README.rst
Labels: documentation

#4147 Fix #3618 s3uploader writing to stdout
  awscli/customizations/s3uploader.py
Labels: cloudformation package-deploy, customization, community

#5576 Add AWS::Serverless::StateMachine resource to cloudformation package command
  awscli/customizations/cloudformation/artifact_exporter.py
  awscli/examples/cloudformation/_package_description.rst
  tests/unit/customizations/cloudformation/test_artifact_exporter.py
Labels: cloudformation package-deploy, cloudformation, community
