Repository aws/aws-cli, pull requests merged in 2023-09, with the labels that each got.

#8161 CLI examples configservice, ec2, pinpoint, payment-cryptography, paym…
  awscli/examples/configservice/put-configuration-recorder.rst
  awscli/examples/ec2/describe-capacity-reservations.rst
  awscli/examples/ec2/describe-export-image-tasks.rst
  awscli/examples/ec2/describe-fleet-history.rst
  awscli/examples/ec2/describe-instance-credit-specifications.rst
  awscli/examples/ec2/describe-instance-event-windows.rst
  awscli/examples/ec2/describe-instance-status.rst
  awscli/examples/ec2/describe-instances.rst
  awscli/examples/ec2/describe-key-pairs.rst
  awscli/examples/ec2/describe-local-gateway-route-table-vpc-associations.rst
  awscli/examples/ec2/describe-security-group-rules.rst
  awscli/examples/ec2/describe-traffic-mirror-targets.rst
  awscli/examples/payment-cryptography-data/decrypt-data.rst
  awscli/examples/payment-cryptography-data/encrypt-data.rst
  awscli/examples/payment-cryptography-data/generate-card-validation-data.rst
  awscli/examples/payment-cryptography-data/generate-mac.rst
  awscli/examples/payment-cryptography-data/generate-pin-data.rst
  awscli/examples/payment-cryptography-data/re-encrypt-data.rst
  awscli/examples/payment-cryptography-data/translate-pin-data.rst
  awscli/examples/payment-cryptography-data/verify-auth-request-cryptogram.rst
  awscli/examples/payment-cryptography-data/verify-card-validation-data.rst
  awscli/examples/payment-cryptography-data/verify-mac.rst
  awscli/examples/payment-cryptography-data/verify-pin-data.rst
  awscli/examples/payment-cryptography/create-alias.rst
  awscli/examples/payment-cryptography/create-key.rst
  awscli/examples/payment-cryptography/delete-alias.rst
  awscli/examples/payment-cryptography/delete-key.rst
  awscli/examples/payment-cryptography/export-key.rst
  awscli/examples/payment-cryptography/get-alias.rst
  awscli/examples/payment-cryptography/get-key.rst
  awscli/examples/payment-cryptography/get-parameters-for-export.rst
  awscli/examples/payment-cryptography/get-parameters-for-import.rst
  awscli/examples/payment-cryptography/get-public-key-certificate.rst
  awscli/examples/payment-cryptography/import-key.rst
  awscli/examples/payment-cryptography/list-aliases.rst
  awscli/examples/payment-cryptography/list-keys.rst
  awscli/examples/payment-cryptography/list-tags-for-resource.rst
  awscli/examples/payment-cryptography/restore-key.rst
  awscli/examples/payment-cryptography/start-key-usage.rst
  awscli/examples/payment-cryptography/stop-key-usage.rst
  awscli/examples/payment-cryptography/tag-resource.rst
  awscli/examples/payment-cryptography/untag-resource.rst
  awscli/examples/payment-cryptography/update-alias.rst
  awscli/examples/pinpoint/update-sms-channel.rst
Labels: documentation

#5508 updating README v2 with instructions for Arm
  README.rst
Labels: documentation, community

#8183 CLI examples directconnect, ec2, iam, iot, lambda, sqs
  awscli/examples/directconnect/create-transit-virtual-interface.rst
  awscli/examples/ec2/assign-private-nat-gateway-address.rst
  awscli/examples/ec2/associate-nat-gateway-address.rst
  awscli/examples/ec2/attach-verified-access-trust-provider.rst
  awscli/examples/ec2/cancel-image-launch-permission.rst
  awscli/examples/ec2/create-carrier-gateway.rst
  awscli/examples/ec2/create-image.rst
  awscli/examples/ec2/create-instance-connect-endpoint.rst
  awscli/examples/ec2/create-verified-access-endpoint.rst
  awscli/examples/ec2/create-verified-access-group.rst
  awscli/examples/ec2/create-verified-access-instance.rst
  awscli/examples/ec2/create-verified-access-trust-provider.rst
  awscli/examples/ec2/delete-instance-connect-endpoint.rst
  awscli/examples/ec2/delete-verified-access-endpoint.rst
  awscli/examples/ec2/delete-verified-access-group.rst
  awscli/examples/ec2/delete-verified-access-instance.rst
  awscli/examples/ec2/delete-verified-access-trust-provider.rst
  awscli/examples/ec2/describe-aws-network-performance-metric-subscription.rst
  awscli/examples/ec2/describe-instance-connect-endpoints.rst
  awscli/examples/ec2/describe-nat-gateways.rst
  awscli/examples/ec2/describe-verified-access-endpoints.rst
  awscli/examples/ec2/describe-verified-access-groups.rst
  awscli/examples/ec2/describe-verified-access-instance-logging-configurations.rst
  awscli/examples/ec2/describe-verified-access-instances.rst
  awscli/examples/ec2/describe-verified-access-trust-providers.rst
  awscli/examples/ec2/detach-verified-access-trust-provider.rst
  awscli/examples/ec2/disable-aws-network-performance-metric-subscription.rst
  awscli/examples/ec2/disable-image-block-public-access.rst
  awscli/examples/ec2/disassociate-nat-gateway-address.rst
  awscli/examples/ec2/enable-aws-network-performance-metric-subscription.rst
  awscli/examples/ec2/enable-image-block-public-access.rst
  awscli/examples/ec2/get-aws-network-performance-data.rst
  awscli/examples/ec2/get-image-block-public-access-state.rst
  awscli/examples/ec2/get-verified-access-endpoint-policy.rst
  awscli/examples/ec2/get-verified-access-group-policy.rst
  awscli/examples/ec2/modify-private-dns-name-options.rst
  awscli/examples/ec2/modify-verified-access-endpoint-policy.rst
  awscli/examples/ec2/modify-verified-access-endpoint.rst
  awscli/examples/ec2/modify-verified-access-group-policy.rst
  awscli/examples/ec2/modify-verified-access-group.rst
  awscli/examples/ec2/modify-verified-access-instance-logging-configuration.rst
  awscli/examples/ec2/modify-verified-access-instance.rst
  awscli/examples/ec2/modify-verified-access-trust-provider.rst
  awscli/examples/ec2/unassign-private-nat-gateway-address.rst
  awscli/examples/ec2/wait/internet-gateway-exists.rst
  awscli/examples/ec2/wait/nat-gateway-deleted.rst
  awscli/examples/iam/create-account-alias.rst
  awscli/examples/iam/create-policy.rst
  awscli/examples/iot/delete-domain-configuration.rst
  awscli/examples/lambda/invoke.rst
  awscli/examples/sqs/cancel-message-move-task.rst
  awscli/examples/sqs/list-message-move-tasks.rst
  awscli/examples/sqs/start-message-move-task.rst
Labels: documentation

#4937 sync: document --delete behavior for excluded files
  awscli/customizations/s3/syncstrategy/delete.py
Labels: s3sync, pr:needs-review
