Repository aws/aws-cli, pull requests merged in 2024-12, with the labels that each got.

#8746 Fix spaces in start-live-tail parameter information
  awscli/customizations/logs/startlivetail.py
Labels: documentation, pr:ready-to-merge

#9122 Fix examples that use the parameter --auto-scaling-group-names
  awscli/examples/autoscaling/describe-auto-scaling-groups.rst
Labels: documentation, pr:needs-review

#9140 [V2] Fix examples that use the parameter --auto-scaling-group-names
  awscli/examples/autoscaling/describe-auto-scaling-groups.rst
Labels: documentation

#8638 Update `Example 6` title for `aws s3 sync` help doc
  awscli/examples/s3/sync.rst
Labels: documentation, pr:needs-review

#9166 CLI examples iam, ivs, sts
  awscli/examples/iam/disable-organizations-root-credentials-management.rst
  awscli/examples/iam/disable-organizations-root-sessions.rst
  awscli/examples/iam/enable-organizations-root-credentials-management.rst
  awscli/examples/iam/enable-organizations-root-sessions.rst
  awscli/examples/iam/list-organizations-features.rst
  awscli/examples/ivs/batch-get-channel.rst
  awscli/examples/ivs/create-channel.rst
  awscli/examples/ivs/get-channel.rst
  awscli/examples/ivs/get-stream-session.rst
  awscli/examples/ivs/update-channel.rst
  awscli/examples/sts/assume-root.rst
Labels: documentation, pr:needs-review
