Repository aws/aws-cli, pull requests merged in 2024-11, with the labels that each got.

#9065 Remove macOS fallback now that setup-python issue is resolved
  .github/workflows/run-tests.yml
Labels: v2

#9072 Updated s3 naming standards.
  docs_styleguide.md
Labels: documentation

#9014 CLI examples apigateway, ecr-public, iam, securityhub
  awscli/examples/apigateway/flush-stage-cache.rst
  awscli/examples/ecr-public/describe-registries.rst
  awscli/examples/ecr-public/describe-repository.rst
  awscli/examples/ecr-public/get-login-password.rst
  awscli/examples/iam/create-policy.rst
  awscli/examples/iam/get-account-authorization-details.rst
  awscli/examples/securityhub/list-configuration-policy-associations.rst
Labels: documentation, pr:needs-review

#9095 [v2] CLI examples apigateway, ecr-public, iam, securityhub
  awscli/examples/apigateway/flush-stage-cache.rst
  awscli/examples/ecr-public/describe-registries.rst
  awscli/examples/ecr-public/describe-repository.rst
  awscli/examples/ecr-public/get-login-password.rst
  awscli/examples/iam/create-policy.rst
  awscli/examples/iam/get-account-authorization-details.rst
  awscli/examples/securityhub/list-configuration-policy-associations.rst
Labels: documentation, v2
