Repository aws/aws-cli, pull requests merged in 2025-05, with the labels that each got.

#9463 Add required field validation to nested structures
  awscli/clidocs.py
  tests/unit/test_clidocs.py
Labels: accessibility

#9488 Updated CLI examples for Systems Manager
  awscli/examples/ssm/put-parameter.rst
Labels: documentation, pr:ready-to-merge

#9473 New CLI examples for RDS Performance Insights
  awscli/examples/pi/create-performance-analysis-report.rst
  awscli/examples/pi/delete-performance-analysis-report.rst
  awscli/examples/pi/describe-dimension-keys.rst
  awscli/examples/pi/get-dimension-key-details.rst
  awscli/examples/pi/get-performance-analysis-report.rst
  awscli/examples/pi/get-resource-metadata.rst
  awscli/examples/pi/list-available-resource-dimensions.rst
  awscli/examples/pi/list-available-resource-metrics.rst
  awscli/examples/pi/list-performance-analysis-reports.rst
  awscli/examples/pi/list-tags-for-resource.rst
  awscli/examples/pi/tag-resource.rst
  awscli/examples/pi/untag-resource.rst
Labels: documentation, pr:needs-review

#9502 Updated CLI example for ELBv2
  awscli/examples/elbv2/modify-listener.rst
Labels: documentation, pr:needs-review

#9510 Updated CLI example for Amazon WorkSpaces
  awscli/examples/workspaces/register-workspace-directory.rst
Labels: documentation, pr:ready-to-merge
