Repository aws/aws-cli, pull requests merged in 2025-01, with the labels that each got.

#9191 Examples for ec2
  awscli/examples/ec2/associate-transit-gateway-multicast-domain.rst
  awscli/examples/ec2/delete-verified-access-endpoint.rst
  awscli/examples/ec2/describe-verified-access-endpoints.rst
  awscli/examples/ec2/disable-address-transfer.rst
  awscli/examples/ec2/disable-aws-network-performance-metric-subscription.rst
  awscli/examples/ec2/disable-fast-launch.rst
  awscli/examples/ec2/disable-image-block-public-access.rst
  awscli/examples/ec2/disable-image-deprecation.rst
  awscli/examples/ec2/disassociate-transit-gateway-multicast-domain.rst
  awscli/examples/ec2/enable-address-transfer.rst
  awscli/examples/ec2/enable-fast-launch.rst
  awscli/examples/ec2/enable-image-deprecation.rst
  awscli/examples/ec2/export-client-vpn-client-configuration.rst
  awscli/examples/ec2/get-aws-network-performance-data.rst
  awscli/examples/ec2/get-capacity-reservation-usage.rst
  awscli/examples/ec2/get-coip-pool-usage.rst
  awscli/examples/ec2/get-groups-for-capacity-reservation.rst
  awscli/examples/ec2/get-network-insights-access-scope-analysis-findings.rst
  awscli/examples/ec2/get-network-insights-access-scope-content.rst
  awscli/examples/ec2/get-transit-gateway-multicast-domain-associations.rst
  awscli/examples/ec2/get-transit-gateway-prefix-list-references.rst
  awscli/examples/ec2/list-images-in-recycle-bin.rst
  awscli/examples/ec2/list-snapshots-in-recycle-bin.rst
  awscli/examples/ec2/modify-availability-zone-group.rst
  awscli/examples/ec2/modify-capacity-reservation.rst
  awscli/examples/ec2/modify-fleet.rst
  awscli/examples/ec2/modify-hosts.rst
  awscli/examples/ec2/modify-instance-capacity-reservation-attributes.rst
  awscli/examples/ec2/modify-instance-maintenance-options.rst
  awscli/examples/ec2/modify-instance-metadata-options.rst
  awscli/examples/ec2/modify-instance-placement.rst
  awscli/examples/ec2/modify-snapshot-tier.rst
  awscli/examples/ec2/modify-transit-gateway-prefix-list-reference.rst
  awscli/examples/ec2/modify-verified-access-endpoint.rst
  awscli/examples/ec2/register-instance-event-notification-attributes.rst
  awscli/examples/ec2/register-transit-gateway-multicast-group-members.rst
  awscli/examples/ec2/register-transit-gateway-multicast-group-sources.rst
  awscli/examples/ec2/restore-image-from-recycle-bin.rst
  awscli/examples/ec2/restore-snapshot-from-recycle-bin.rst
  awscli/examples/ec2/restore-snapshot-tier.rst
  awscli/examples/ec2/search-transit-gateway-multicast-groups.rst
  awscli/examples/ec2/start-network-insights-access-scope-analysis.rst
Labels: documentation, pr:needs-review

#9180 CLI examples for guardduty
  awscli/examples/guardduty/accept-invitation.rst
  awscli/examples/guardduty/archive-findings.rst
  awscli/examples/guardduty/create-filter.rst
  awscli/examples/guardduty/create-ip-set.rst
  awscli/examples/guardduty/create-publishing-destination.rst
  awscli/examples/guardduty/create-threat-intel-set.rst
  awscli/examples/guardduty/disassociate-from-master-account.rst
  awscli/examples/guardduty/get-ip-set.rst
  awscli/examples/guardduty/get-master-account.rst
  awscli/examples/guardduty/list-members.rst
  awscli/examples/guardduty/update-ip-set.rst
Labels: documentation, pr:ready-to-merge

#9178 Examples for apigateway, ssm, verifiedpermissions
  awscli/examples/apigateway/create-domain-name-access-association.rst
  awscli/examples/apigateway/create-domain-name.rst
  awscli/examples/apigateway/delete-domain-name-access-association.rst
  awscli/examples/apigateway/get-domain-name-access-associations.rst
  awscli/examples/apigateway/get-domain-name.rst
  awscli/examples/apigateway/get-domain-names.rst
  awscli/examples/apigateway/reject-domain-name-access-association.rst
  awscli/examples/ssm/deregister-managed-instance.rst
  awscli/examples/verifiedpermissions/create-policy-template.rst
Labels: documentation, pr:needs-review

#8828 Add note on chunk size adjustment behavior
  awscli/topics/s3-config.rst
Labels: documentation, s3, pr:needs-review

#8765 Correct JSON sample output of sts assume-role-with-web-identity command
  awscli/examples/sts/assume-role-with-web-identity.rst
Labels: documentation, pr:needs-review

#9096 Update to HealthLake examples
  awscli/examples/healthlake/create-fhir-datastore.rst
  awscli/examples/healthlake/delete-fhir-datastore.rst
  awscli/examples/healthlake/describe-fhir-datastore.rst
  awscli/examples/healthlake/describe-fhir-export-job.rst
  awscli/examples/healthlake/describe-fhir-import-job.rst
  awscli/examples/healthlake/list-fhir-datastores.rst
  awscli/examples/healthlake/list-fhir-export-jobs.rst
  awscli/examples/healthlake/list-fhir-import-jobs.rst
  awscli/examples/healthlake/list-tags-for-resource.rst
  awscli/examples/healthlake/start-fhir-export-job.rst
  awscli/examples/healthlake/start-fhir-import-job.rst
  awscli/examples/healthlake/tag-resource.rst
  awscli/examples/healthlake/untag-resource.rst
Labels: documentation, pr:needs-review

#8936 docs: update create-vpc-endpoint.rst
  awscli/examples/ec2/create-vpc-endpoint.rst
Labels: documentation, pr:needs-review

#9116 add API command examples for Amazon CloudWatch observabilityadmin service
  awscli/examples/observabilityadmin/get-telemetry-evaluation-status-for-organization.rst
  awscli/examples/observabilityadmin/get-telemetry-evaluation-status.rst
  awscli/examples/observabilityadmin/list-resource-telemetry-for-organization.rst
  awscli/examples/observabilityadmin/list-resource-telemetry.rst
  awscli/examples/observabilityadmin/start-telemetry-evaluation-for-organization.rst
  awscli/examples/observabilityadmin/start-telemetry-evaluation.rst
  awscli/examples/observabilityadmin/stop-telemetry-evaluation-for-organization.rst
  awscli/examples/observabilityadmin/stop-telemetry-evaluation.rst
Labels: documentation, pr:needs-review

#9085 CLI examples for cloudfront, ec2, ivs, rds, securitylake
  awscli/examples/cloudfront/create-distribution-with-tags.rst
  awscli/examples/cloudfront/get-distribution.rst
  awscli/examples/ec2/accept-address-transfer.rst
  awscli/examples/ec2/allocate-hosts.rst
  awscli/examples/ec2/associate-address.rst
  awscli/examples/ec2/authorize-security-group-egress.rst
  awscli/examples/ec2/authorize-security-group-ingress.rst
  awscli/examples/ec2/cancel-capacity-reservation.rst
  awscli/examples/ec2/cancel-spot-fleet-requests.rst
  awscli/examples/ec2/copy-snapshot.rst
  awscli/examples/ec2/create-capacity-reservation.rst
  awscli/examples/ec2/create-replace-root-volume-task.rst
  awscli/examples/ec2/create-restore-image-task.rst
  awscli/examples/ec2/create-spot-datafeed-subscription.rst
  awscli/examples/ec2/create-tags.rst
  awscli/examples/ec2/create-traffic-mirror-filter-rule.rst
  awscli/examples/ec2/create-traffic-mirror-filter.rst
  awscli/examples/ec2/create-traffic-mirror-session.rst
  awscli/examples/ec2/create-traffic-mirror-target.rst
  awscli/examples/ec2/create-transit-gateway-prefix-list-reference.rst
  awscli/examples/ec2/create-verified-access-endpoint.rst
  awscli/examples/ec2/create-vpc-endpoint-service-configuration.rst
  awscli/examples/ec2/create-vpc-endpoint.rst
  awscli/examples/ec2/describe-vpc-endpoint-service-configurations.rst
  awscli/examples/ec2/describe-vpc-endpoint-services.rst
  awscli/examples/ec2/describe-vpc-endpoints.rst
  awscli/examples/rds/download-db-log-file-portion.rst
  awscli/examples/securitylake/create-aws-log-source.rst
  awscli/examples/securitylake/create-custom-log-source.rst
  awscli/examples/securitylake/create-subscriber-data-access.rst
  awscli/examples/securitylake/create-subscriber-query-access.rst
  awscli/examples/securitylake/create-subscriber.rst
  awscli/examples/securitylake/delete-aws-log-source.rst
  awscli/examples/securitylake/delete-custom-log-source.rst
Labels: documentation, pr:needs-review

#9227 Replaced /CodeDeployDemoBucket/ with amzn-s3-demo-bucket
  awscli/examples/deploy/batch-get-deployments.rst
  awscli/examples/deploy/create-deployment.rst
  awscli/examples/deploy/get-application-revision.rst
  awscli/examples/deploy/get-deployment.rst
  awscli/examples/deploy/list-application-revisions.rst
  awscli/examples/deploy/push.rst
  awscli/examples/deploy/register-application-revision.rst
Labels: documentation, pr:needs-review

#9144 Updated AWS CLI command to describe EKS cluster
  awscli/examples/eks/describe-cluster.rst
Labels: documentation, pr:needs-review

#9221 Replaced /myBucket/ with amzn-s3-demo-bucket
  awscli/examples/emr/create-cluster-examples.rst
  awscli/examples/emr/schedule-hbase-backup.rst
  awscli/examples/importexport/create-job.rst
  awscli/examples/importexport/get-shipping-label.rst
  awscli/examples/importexport/get-status.rst
Labels: documentation, pr:needs-review

#9219 Replaced /mybucket2/ with amzn-s3-demo-bucket2
  awscli/examples/cloudtrail/put-event-selectors.rst
  awscli/examples/s3/cp.rst
  awscli/examples/s3/ls.rst
  awscli/examples/s3/mv.rst
  awscli/examples/s3/sync.rst
Labels: documentation, pr:needs-review

#9175 Add CLI examples for CloudWatch OAM and Synthetics
  awscli/examples/oam/create-link.rst
  awscli/examples/oam/create-sink.rst
  awscli/examples/oam/delete-link.rst
  awscli/examples/oam/delete-sink.rst
  awscli/examples/oam/get-link.rst
  awscli/examples/oam/get-sink-policy.rst
  awscli/examples/oam/get-sink.rst
  awscli/examples/oam/list-attached-links.rst
  awscli/examples/oam/list-links.rst
  awscli/examples/oam/list-sinks.rst
  awscli/examples/oam/list-tags-for-resource.rst
  awscli/examples/oam/put-sink-policy.rst
  awscli/examples/oam/tag-resource.rst
  awscli/examples/oam/untag-resource.rst
  awscli/examples/oam/update-link.rst
  awscli/examples/synthetics/associate-resource.rst
  awscli/examples/synthetics/create-canary.rst
  awscli/examples/synthetics/create-group.rst
  awscli/examples/synthetics/delete-canary.rst
  awscli/examples/synthetics/delete-group.rst
  awscli/examples/synthetics/describe-canaries-last-run.rst
  awscli/examples/synthetics/describe-canaries.rst
  awscli/examples/synthetics/describe-runtime-versions.rst
  awscli/examples/synthetics/disassociate-resource.rst
  awscli/examples/synthetics/get-canary-runs.rst
  awscli/examples/synthetics/get-canary.rst
  awscli/examples/synthetics/get-group.rst
  awscli/examples/synthetics/list-associated-groups.rst
  awscli/examples/synthetics/list-group-resources.rst
  awscli/examples/synthetics/list-groups.rst
  awscli/examples/synthetics/list-tags-for-resource.rst
  awscli/examples/synthetics/start-canary.rst
  awscli/examples/synthetics/stop-canary.rst
  awscli/examples/synthetics/tag-resource.rst
  awscli/examples/synthetics/untag-resource.rst
  awscli/examples/synthetics/update-canary.rst
Labels: documentation, pr:ready-to-merge

#9206 Lint and format awscli/autoprompt
  awscli/autoprompt/core.py
  awscli/autoprompt/doc.py
  awscli/autoprompt/factory.py
  awscli/autoprompt/filters.py
  awscli/autoprompt/history.py
  awscli/autoprompt/logger.py
  awscli/autoprompt/output.py
  awscli/autoprompt/prompttoolkit.py
  awscli/autoprompt/widgets.py
Labels: pr:needs-review

#9218 Replaced /test-bucket/ with amzn-s3-demo-bucket
  awscli/examples/ivs-realtime/create-storage-configuration.rst
  awscli/examples/ivs-realtime/get-storage-configuration.rst
  awscli/examples/ivs-realtime/list-storage-configurations.rst
Labels: documentation, pr:needs-review

#9086 CLI examples cloudtrail, ec2, ecs, macie2
  awscli/examples/cloudtrail/create-subscription.rst
  awscli/examples/cloudtrail/create-trail.rst
  awscli/examples/cloudtrail/describe-trails.rst
  awscli/examples/cloudtrail/put-event-selectors.rst
  awscli/examples/cloudtrail/update-subscription.rst
  awscli/examples/cloudtrail/update-trail.rst
  awscli/examples/ec2/describe-capacity-reservations.rst
  awscli/examples/ec2/describe-instance-image-metadata.rst
  awscli/examples/ecs/describe-service-deployments.rst
  awscli/examples/ecs/describe-service-revisions.rst
  awscli/examples/ecs/list-service-deployments.rst
  awscli/examples/macie2/describe-buckets.rst
Labels: documentation, pr:ready-to-merge

#9233 [v2] CLI examples cloudtrail, ec2, ecs, macie2
  awscli/examples/cloudtrail/create-trail.rst
  awscli/examples/cloudtrail/describe-trails.rst
  awscli/examples/cloudtrail/put-event-selectors.rst
  awscli/examples/cloudtrail/update-trail.rst
  awscli/examples/ec2/describe-capacity-reservations.rst
  awscli/examples/ec2/describe-instance-image-metadata.rst
  awscli/examples/ecs/describe-service-deployments.rst
  awscli/examples/ecs/describe-service-revisions.rst
  awscli/examples/ecs/list-service-deployments.rst
  awscli/examples/macie2/describe-buckets.rst
Labels: documentation, pr:work-in-progress

#9015 CLI examples for ds-data, ecr-public
  awscli/examples/ds-data/add-group-member.rst
  awscli/examples/ds-data/create-group.rst
  awscli/examples/ds-data/create-user.rst
  awscli/examples/ds-data/delete-group.rst
  awscli/examples/ds-data/delete-user.rst
  awscli/examples/ds-data/describe-group.rst
  awscli/examples/ds-data/describe-user.rst
  awscli/examples/ds-data/disable-directory-data-access.rst
  awscli/examples/ds-data/disable-user.rst
  awscli/examples/ds-data/enable-directory-data-access.rst
  awscli/examples/ds-data/list-group-members.rst
  awscli/examples/ds-data/list-groups-for-member.rst
  awscli/examples/ds-data/list-groups.rst
  awscli/examples/ds-data/list-users.rst
  awscli/examples/ds-data/remove-group-member.rst
  awscli/examples/ds-data/reset-user-password.rst
  awscli/examples/ds-data/search-groups.rst
  awscli/examples/ds-data/search-users.rst
  awscli/examples/ds-data/update-group.rst
  awscli/examples/ds-data/update-user.rst
  awscli/examples/ecr-public/get-registry-catalog-data.rst
  awscli/examples/ecr-public/get-repository-catalog-data.rst
  awscli/examples/ecr-public/list-tags-for-resource.rst
  awscli/examples/ecr-public/put-registry-catalog-data.rst
  awscli/examples/ecr-public/put-repository-catalog-data.rst
  awscli/examples/ecr-public/tag-resource.rst
  awscli/examples/ecr-public/untag-resource.rst
Labels: documentation, pr:ready-to-merge

#9225 Replaced /awsExampleBucket/ with amzn-s3-demo-bucket
  awscli/examples/qldb/describe-journal-s3-export.rst
  awscli/examples/qldb/export-journal-to-s3.rst
  awscli/examples/qldb/list-journal-s3-exports-for-ledger.rst
  awscli/examples/qldb/list-journal-s3-exports.rst
Labels: documentation, pr:needs-review

#9127 Add CLI examples for CloudWatch NetworkFlowMonitor
  awscli/examples/networkflowmonitor/create-monitor.rst
  awscli/examples/networkflowmonitor/create-scope.rst
  awscli/examples/networkflowmonitor/delete-monitor.rst
  awscli/examples/networkflowmonitor/delete-scope.rst
  awscli/examples/networkflowmonitor/get-monitor.rst
  awscli/examples/networkflowmonitor/get-query-results-workload-insights-top-contributors-data.rst
  awscli/examples/networkflowmonitor/get-query-results-workload-insights-top-contributors.rst
  awscli/examples/networkflowmonitor/get-query-status-monitor-top-contributors.rst
  awscli/examples/networkflowmonitor/get-query-status-workload-insights-top-contributors-data.rst
  awscli/examples/networkflowmonitor/get-query-status-workload-insights-top-contributors.rst
  awscli/examples/networkflowmonitor/get-scope.rst
  awscli/examples/networkflowmonitor/list-monitors.rst
  awscli/examples/networkflowmonitor/list-scopes.rst
  awscli/examples/networkflowmonitor/list-tags-for-resource.rst
  awscli/examples/networkflowmonitor/start-query-monitor-top-contributors.rst
  awscli/examples/networkflowmonitor/start-query-workload-insights-top-contributors-data.rst
  awscli/examples/networkflowmonitor/start-query-workload-insights-top-contributors.rst
  awscli/examples/networkflowmonitor/stop-query-monitor-top-contributors.rst
  awscli/examples/networkflowmonitor/stop-query-workload-insights-top-contributors-data.rst
  awscli/examples/networkflowmonitor/stop-query-workload-insights-top-contributors.rst
  awscli/examples/networkflowmonitor/tag-resource.rst
  awscli/examples/networkflowmonitor/untag-resource.rst
  awscli/examples/networkflowmonitor/update-monitor.rst
Labels: documentation, pr:needs-review
