Repository aws/aws-cli, pull requests merged in 2025-03, with the labels that each got.

#9339 Examples ds-data
  awscli/examples/ds-data/create-group.rst
Labels: documentation, pr:needs-review

#9220 Replaced /mybucket/ with amzn-s3-demo-bucket
  awscli/examples/cloudformation/_package_description.rst
  awscli/examples/emr/add-steps.rst
  awscli/examples/emr/create-cluster-examples.rst
  awscli/examples/rds/cancel-export-task.rst
  awscli/examples/rds/describe-export-tasks.rst
  awscli/examples/rds/restore-db-cluster-from-s3.rst
  awscli/examples/rds/start-export-task.rst
  awscli/examples/s3/_concepts.rst
  awscli/examples/s3/cp.rst
  awscli/examples/s3/ls.rst
  awscli/examples/s3/mb.rst
  awscli/examples/s3/mv.rst
  awscli/examples/s3/rb.rst
  awscli/examples/s3/rm.rst
  awscli/examples/s3/sync.rst
  awscli/examples/s3api/get-bucket-policy.rst
Labels: documentation, pr:needs-review

#8510 Update get-merge-commit.rst
  awscli/examples/codecommit/get-merge-commit.rst
Labels: documentation, pr:ready-to-merge

#9312 CLI examples ecs, cognito-idp
  awscli/examples/cognito-idp/get-identity-provider-by-identifier.rst
  awscli/examples/cognito-idp/get-log-delivery-configuration.rst
  awscli/examples/cognito-idp/get-signing-certificate.rst
  awscli/examples/cognito-idp/get-ui-customization.rst
  awscli/examples/cognito-idp/get-user-attribute-verification-code.rst
  awscli/examples/cognito-idp/get-user-auth-factors.rst
  awscli/examples/cognito-idp/get-user-pool-mfa-config.rst
  awscli/examples/cognito-idp/get-user.rst
  awscli/examples/cognito-idp/global-sign-out.rst
  awscli/examples/cognito-idp/initiate-auth.rst
  awscli/examples/cognito-idp/list-devices.rst
  awscli/examples/cognito-idp/list-groups.rst
  awscli/examples/cognito-idp/list-identity-providers.rst
  awscli/examples/cognito-idp/list-resource-servers.rst
  awscli/examples/cognito-idp/list-tags-for-resource.rst
  awscli/examples/cognito-idp/list-user-import-jobs.rst
  awscli/examples/cognito-idp/list-user-pool-clients.rst
  awscli/examples/cognito-idp/list-user-pools.rst
  awscli/examples/cognito-idp/list-users.rst
  awscli/examples/cognito-idp/list-web-authn-credentials.rst
  awscli/examples/cognito-idp/respond-to-auth-challenge.rst
  awscli/examples/cognito-idp/revoke-token.rst
  awscli/examples/cognito-idp/set-log-delivery-configuration.rst
  awscli/examples/cognito-idp/set-risk-configuration.rst
  awscli/examples/cognito-idp/set-ui-customization.rst
  awscli/examples/cognito-idp/set-user-mfa-preference.rst
  awscli/examples/cognito-idp/set-user-pool-mfa-config.rst
  awscli/examples/cognito-idp/start-user-import-job.rst
  awscli/examples/cognito-idp/start-web-authn-registration.rst
  awscli/examples/cognito-idp/stop-user-import-job.rst
  awscli/examples/ecs/create-cluster.rst
  awscli/examples/ecs/put-account-setting.rst
  awscli/examples/ecs/update-cluster-settings.rst
  awscli/examples/ecs/update-service.rst
Labels: documentation, pr:needs-review, changes-requested

#9323 CLI examples cognito-idp, ec2, vpc-lattice
  awscli/examples/cognito-idp/tag-resource.rst
  awscli/examples/cognito-idp/untag-resource.rst
  awscli/examples/cognito-idp/update-identity-provider.rst
  awscli/examples/cognito-idp/update-managed-login-branding.rst
  awscli/examples/cognito-idp/update-user-pool-client.rst
  awscli/examples/cognito-idp/update-user-pool-domain.rst
  awscli/examples/cognito-idp/verify-software-token.rst
  awscli/examples/cognito-idp/verify-user-attribute.rst
  awscli/examples/ec2/associate-security-group-vpc.rst
  awscli/examples/ec2/create-vpc-endpoint.rst
  awscli/examples/ec2/describe-security-group-vpc-associations.rst
  awscli/examples/ec2/describe-vpc-endpoint-associations.rst
  awscli/examples/ec2/disable-image-deregistration-protection.rst
  awscli/examples/ec2/disassociate-security-group-vpc.rst
  awscli/examples/ec2/enable-image-deregistration-protection.rst
  awscli/examples/vpc-lattice/create-resource-configuration.rst
  awscli/examples/vpc-lattice/create-resource-gateway.rst
  awscli/examples/vpc-lattice/delete-resource-configuration.rst
  awscli/examples/vpc-lattice/delete-resource-gateway.rst
  awscli/examples/vpc-lattice/get-resource-configuration.rst
  awscli/examples/vpc-lattice/get-resource-gateway.rst
  awscli/examples/vpc-lattice/list-resource-configurations.rst
  awscli/examples/vpc-lattice/list-resource-endpoint-associations.rst
  awscli/examples/vpc-lattice/list-resource-gateways.rst
  awscli/examples/vpc-lattice/list-service-network-vpc-endpoint-associations.rst
Labels: documentation, pr:needs-review

#9376 CLI example update to invoke for v2 branch
  awscli/examples/lambda/invoke.rst
Labels: documentation, pr:ready-to-merge

#9329 CLI examples ecs, servicediscovery
  awscli/examples/ecs/create-service.rst
  awscli/examples/ecs/run-task.rst
  awscli/examples/ecs/start-task.rst
  awscli/examples/ecs/update-service.rst
  awscli/examples/servicediscovery/create-http-namespace.rst
  awscli/examples/servicediscovery/create-public-dns-namespace.rst
  awscli/examples/servicediscovery/delete-service-attributes.rst
  awscli/examples/servicediscovery/discover-instances-revision.rst
  awscli/examples/servicediscovery/discover-instances.rst
  awscli/examples/servicediscovery/get-instance.rst
  awscli/examples/servicediscovery/get-instances-health-status.rst
  awscli/examples/servicediscovery/get-namespace.rst
  awscli/examples/servicediscovery/get-operation.rst
  awscli/examples/servicediscovery/get-service-attributes.rst
  awscli/examples/servicediscovery/get-service.rst
  awscli/examples/servicediscovery/list-operations.rst
  awscli/examples/servicediscovery/list-tags-for-resource.rst
  awscli/examples/servicediscovery/tag-resource.rst
  awscli/examples/servicediscovery/untag-resource.rst
  awscli/examples/servicediscovery/update-http-namespace.rst
  awscli/examples/servicediscovery/update-instance-custom-health-status.rst
  awscli/examples/servicediscovery/update-private-dns-namespace.rst
  awscli/examples/servicediscovery/update-public-dns-namespace.rst
  awscli/examples/servicediscovery/update-service-attributes.rst
  awscli/examples/servicediscovery/update-service.rst
Labels: documentation, pr:needs-review

#9410 cli examples for ivs realtime
  awscli/examples/ivs-realtime/create-stage.rst
  awscli/examples/ivs-realtime/get-composition.rst
  awscli/examples/ivs-realtime/get-stage.rst
  awscli/examples/ivs-realtime/start-composition.rst
  awscli/examples/ivs-realtime/update-stage.rst
Labels: documentation, pr:needs-review
